# Node.js Dockerfile
FROM node:14-slim

# Set the working directory
WORKDIR /usr/src/app

ENV EXECUTABLE="tempCode"
ENV INPUT=""

# Command to run the Node.js script
CMD ["sh", "-c", "echo -e \"${INPUT}\" | node ${EXECUTABLE}.js"]
