# Python Dockerfile
FROM python:latest

# Set the working directory
WORKDIR /usr/src/app

ENV EXECUTABLE=tempCode

# Command to run the Python script
CMD ["sh", "-c", "cat ${EXECUTABLE}.txt | python ${EXECUTABLE}.py"]
